pipeline {
    agent any
    stages {
        stage('Newman tests') {
        steps {
                sh ''' 
                node --version
                cd api/newman
                newman run examen.postman_collection.json -e examenprac.postman_environment.json
                cd
                '''
            }
            }
          }}
            
  
            
        
    

