pipeline {
    agent any
    stages {
        stage('Newman tests') {
        steps {
                sh ''' 
                node --version
                cd api/newman
                newman run examen.postman_collection.json -e examenprac.postman_environment.json
                cd
                '''
            }
            }
            stage('jmeter tests') {
        steps {
                sh ''' 
                
                cd load
                export PATH=/home/pjcalvov/jmeter/apache-jmeter-5.3/bin:$PATH
                jmeter -n -t Examen Test Plan.jmx
                cd
                '''
            }
            }
          }}
            
  
            
        
    

